import Providers from "./providers";
import "./globals.css";

export const metadata = {
    title: "Derek Ma",
    description: "Generated by create next app"
};

type Props = {
    children: React.ReactNode;
};

export default function Layout({ children }: Props) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
